---

- name: "Create backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive backend build files"
  unarchive:
    src: build.tar.gz
    dest: ~/backend-app

- name: "Install dependencies"
  shell: |
    cd ~/backend-app
    npm i

- name: "Execute app using pm2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js
  register: execute_app

- name: print message
  debug:
    msg: "{{ execute_app.stdout_lines }}"


- name: "Config pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu